image: ubuntu:20.04

services:
  - name: splunk/splunk:8.4.0.1
    alias: splunk

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends python3.7 python3-pip
  - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - python3 --version
