image:
  name: splunk/splunk:8.0.4.1-debian
  entrypoint: [""]

variables:
  SPLUNK_START_ARGS: --accept-license
  SPLUNK_PASSWORD: test_cicd_splunk_password
  SPLUNK_HOME: /opt/splunk
  SPLUNK_USER: splunk

before_script:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends python3.7 python3-pip
  - sudo pip3 install -r requirements.txt
  #- "/sbin/entrypoint.sh start-and-exit"

test:
  stage: test
  script:
    - pip3 install -r test-requirements.txt
    - python3 -m pytest
