image: ubuntu:20.04

variables:
  SPLUNK_START_ARGS: --accept-license
  SPLUNK_PASSWORD: test_cicd_splunk_password

services:
  - name: splunk/splunk:8.0.4.1
    alias: splunk

before_script:
  - apt-get update
  - apt-get install -y --no-install-recommends python3.7 python3-pip
  - pip3 install -r requirements.txt

test:
  stage: test
  script:
    - pip3 install -r test-requirements.txt
    - python3 -m pytest
