image:
  name: splunk/splunk:8.0.4.1-debian
  entrypoint: [""]

variables:
  SPLUNK_START_ARGS: --accept-license
  SPLUNK_PASSWORD: test_cicd_splunk_password
  SPLUNK_HOME: /opt/splunk
  SPLUNK_USER: splunk
  SPLUNK_DEFAULT_DIR: /tmp/defaults
  SPLUNK_DEFAULT_FILE: $SPLUNK_DEFAULT_DIR/default.yml
  GITLAB_DEFAULT_FILE: .gitlab-ci-files/default.yml

before_script:
  - sudo apt-get update
  - sudo apt-get install -y --no-install-recommends python3.7 python3-pip python3-setuptools
  - sudo pip3 install -r requirements.txt
  - mkdir -p $SPLUNK_DEFAULT_DIR
  - cp $GITLAB_DEFAULT_FILE $SPLUNK_DEFAULT_FILE
  - "/sbin/entrypoint.sh start-and-exit"

test:
  stage: test
  script:
    - pip3 install -r test-requirements.txt
    - python3 -m pytest
